#!/usr/bin/env bash
set -e

mkdir $HOME/bin
export PATH="$HOME/bin:$PATH"
curl -s https://ohmyposh.dev/install.sh | bash -s -- -d $HOME/bin
oh-my-posh font install
oh-my-posh get shell

cat << 'EOF' >> ~/.zshrc
eval "$(oh-my-posh init zsh --config ~/themes/star.omp.json)"

if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
  eval "$(oh-my-posh init zsh)"
fi
EOF

chsh -s $(which zsh)
source ~/.zshrc




# zoxide (z)
# https://github.com/ajeetdsouza/zoxide?tab=readme-ov-file
# Check if the shell is Bash or Zsh
if [ "$(basename "$SHELL")" = "bash" ]; then
    curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
    eval "$(zoxide init bash)"
    echo 'eval "$(zoxide init bash)"' >> ~/.bashrc
elif [ "$(basename "$SHELL")" = "zsh" ]; then
    curl -sS https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | zsh
    eval "$(zoxide init zsh)"
    echo 'eval "$(zoxide init zsh)"' >> ~/.zshrc
fi
echo PATH=" /home/tn/.local/bin:$PATH"
z -h


# eza
# https://github.com/eza-community/eza

sudo apt-get install -y fzf

sudo apt update
sudo apt install -y gpg

sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg

echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza
eza -l

# oh my tmux
cd
git clone https://github.com/gpakosz/.tmux.git
ln -s -f .tmux/.tmux.conf
cp .tmux/.tmux.conf.local .

echo 'alias mux=tmux' >> ~/.bashrc
