#!/usr/bin/env bash
set -e

# install python and pip
sudo apt-get install software-properties-common
# sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3-pip

# Check if the shell is Bash or Zsh
if [ "$(basename "$SHELL")" = "bash" ]; then
    echo "alias python=python3" >> ~/.bashrc
    echo "alias pip=pip3" >> ~/.bashrc
    source ~/.bashrc
elif [ "$(basename "$SHELL")" = "zsh" ]; then
    echo "alias python=python3" >> ~/.zshrc
    echo "alias pip=pip3" >> ~/.zshrc
    source ~/.zshrc
fi

python --version
python3 --version

pip --version
pip3 --version

sudo apt install python3.11-venv
python3 -m venv venv
source venv/bin/activate

pip install pylint yamllint


