#!/usr/bin/env bash

set -e

# install python and pip
sudo apt-get install software-properties-common
# sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3-pip

echo "alias python=python3" >> ~/.zshrc
echo "alias pip=pip3" >> ~/.zshrc

source ~/.zshrc

python --version
python3 --version

alias python=python3
alias python3=python3

pip --version
pip3 --version

alias pip=pip3
alias pip3=pip3
